export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";

export const LOAD_CURRENT_PRODUCT = "LOAD_CURRENT_PRODUCT";
export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";

export const LOAD_PRODUCT_ITEMS = "LOAD_PRODUCT_ITEMS";
export const ADD_PRODUCT_ITEM = "ADD_PRODUCT_ITEM";
export const UPDATE_PRODUCT_ITEM = "UPDATE_PRODUCT_ITEM";
export const REMOVE_PRODUCT_ITEM = "REMOVE_PRODUCT_ITEM";
